### ISSUE TITLE
add a 'run all tests' commands for maven and npm

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#10]
When evaluating the Vaadin Connect base starter...
 - ... as a frontend developer I want to run tests with `npm run test` so that I do not have to read any docs and can apply the default approach common for frontend projects.
 - ... as a Java developer I want to run tests with `./mvnw verify` so that I do not have to read any docs and can apply the default approach common for Java / Maven projects.

DoD:
 - running `npm run test` or `./mvnw verify` when the backend is not started yet:
   - runs the backend unit tests
   - runs the frontend unit tests
   - starts the backend (in the dev mode)
   - runs the end-to-end tests
   - stops the backend after the end-to-end tests are completed
 - the README is updated with the accurate 'how to run tests' information

**Comment by platosha** [comment]
It should still be possible to run individually:
- frontend unit tests with `npm`
- e2e tests with `npm`
- backend unit tests with `./mvnw`
