### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by soberich** [vaadin/base-starter-connect#112]
Is this abandoned?
I think this is the best approach, when it came out in "labs" (https://vaadin.com/labs/vaadin-connect) I was thinking "that's it - finally they did it!", but I see it's not moving...

**Comment by Haprog** [comment]
Please see my answer here https://github.com/vaadin/vaadin-connect/issues/440#issuecomment-671252558

**Comment by soberich** [comment]
Indeed this is confusing.
Thank you.
