### ISSUE TITLE
Add login form

### ISSUE THREAD

**Issue by manolo** [vaadin/base-starter-connect#19]
Right now the app has hardcoded the login process. Real apps should have a way for getting credentials from user.

**Comment by vlukashov** [comment]
Let's estimate this task assuming that we can use the `<vaadin-login>` component. In that scenario the DoD would be:
 - the default credentials provider in the base starter renders an overlay with a login form using the [`<vaadin-login-overlay>`](https://cdn.vaadin.com/vaadin-login/1.0.0-alpha3/demo/#element-basic-demos) component
 - the `stayLoggedIn` is assumed to be true (the `<vaadin-login>` component does not have a UI to ask for this option)
 - the 'forgot password' link is not shown

**Comment by vlukashov** [comment]
update the integration tests so that they click through the login form
