### ISSUE TITLE
npm script to start Swagger UI to browse the backend APIs

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#22]
When exploring a Vaadin Connect app I want to have a short command that starts an interactive API browser showing the backend APIs so that I can check the available API methods and call them without writing JS code for that.

DoD:
 - there is a `apibrowser` npm script defined in package.json
 - running the script starts a Swagger UI server on localhost (on a different port than the backend or the frontend)
 - when the Swagger UI server is opened it shows the backend API of the project (no manual step to select / open an OpenAPI spec file is necessary)
 - applies both to the starter and the demo app

**Comment by vlukashov** [comment]
With the Swagger UI [docker image](https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/#docker) the command would be `docker run -p 3000:8080 -e SWAGGER_JSON=/target/generated-resources/openapi.json -v /absolute/path/to/vaadin-connect-project/target:/target swaggerapi/swagger-ui` but we should not expect users to have docker installed on their machines to run the API browser. The idea with this task is to use the an [express-based solution with either swagger-ui or swagger-ui-dist](https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation).

**Comment by SomeoneToIgnore** [comment]
As discussed, due to CORS restrictions enabled on the server, another approach will be investigated: serve swagger ui as part of the Spring backend we have, using the https://mvnrepository.com/artifact/org.webjars/swagger-ui/3.20.1 webjar.

The support should not include retrieving oauth token or different location for the OpenApi json file location support.

**Comment by SomeoneToIgnore** [comment]
Both approaches are possible to implement, npm one seems to be easier and more flexible, hence picked for final implementation.
