### ISSUE TITLE
add an integration test

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#5]
When getting started with the Vaadin Connect base starter I want to see an example of an end-to-end integration test so that I do not have to put effort into researching how to add a new end-to-end test and how to run it.

DoD:
 - there is an end-to-end integration test that emulates an end user interaction with the app (frontend and backend) and verifies that it works as expected. The test scenario can be as simple as `when I type a name into the text field and press the 'click me' button, the label is updated with the 'Hello, name!' text within 1 second after the click`.
 - there is a `test:e2e` npm script that runs the end-to-end test in the local Chrome browser (assuming that backend is already running)
 - the `./mvnw verify` command starts the backend, runs end-to-end tests, and stops the backend after that
 - the README is updated to cover:
   - where in the project are end-to-end tests
   - how to run them
   - what test runner is used, what helper APIs are available for tests

**Comment by SomeoneToIgnore** [comment]
* configure CI system that it's able to run the tests
