### ISSUE TITLE
Add livereload script in devmode

### ISSUE THREAD

**Issue by manolo** [vaadin/base-starter-connect#53]
To avoid the user installing livereload extension, we might rewrite `index.html` by adding `<script src="http://localhost:35729/livereload.js"></script>` 

We might consider some webpack plugin like https://www.npmjs.com/package/webpack-livereload-plugin

**Comment by vlukashov** [comment]
The live reload feature was mentioned in the discussion about how to set up the dev mode. See #229 for details.
