### ISSUE TITLE
Does not start on Windows

### ISSUE THREAD

**Issue by platosha** [vaadin/base-starter-connect#76]
Running `npm start` on Windows results in an error.

One reason is that the `mvn` might not be found in the `PATH`. Suggestion is to use `./mvnw` or `mvnw.cmd` in the `scripts/start/backend.js` for the Maven binary depending on the platform.

Fix any other startup errors too.

**Comment by manolo** [comment]
perhaps instead of figuring out what to execute you can call directly to the wrapper, this command should work in any platform
`java -classpath .mvn/wrapper/maven-wrapper.jar -Dmaven.home=. -Dmaven.multiModuleProjectDirectory=. org.apache.maven.wrapper.MavenWrapperMain compile`

**Comment by vlukashov** [comment]
> perhaps instead of figuring out what to execute you can call directly to the wrapper, this command should work in any platform
> `java -classpath .mvn/wrapper/maven-wrapper.jar -Dmaven.home=. -Dmaven.multiModuleProjectDirectory=. org.apache.maven.wrapper.MavenWrapperMain compile`

Please be careful with calling the maven wrapper .jar directly. Essentially, the `mvnw` / `mvnw.cmd` script does exactly that, but it also checks for a bunch of corner cases to make it more resilient. Calling the .jar directly, without going through the same checks, could make the solution fragile.

**Comment by platosha** [comment]
A similar problem exists with `npm`, you have to spawn `npm.cmd` on Windows. I found the `cross-spawn` cross platform spawn adapter on npm, seems to work really well about this issue.
