### ISSUE TITLE
Spring boot remains running if api browser startup fails

### ISSUE THREAD

**Issue by Artur-** [vaadin/base-starter-connect#80]
If you run `npm start` when port 8082 is in use, the project will fail to start:
```
 🌀  Vaadin Connect API browser is starting ...
...
Error: listen EADDRINUSE: address already in use 127.0.0.1:8082
...
 🚫  Vaadin Connect Unable to continue 
```

but Spring Boot remains running on port 8080

**Comment by SomeoneToIgnore** [comment]
1. No Spring boot instances remain running after https://github.com/vaadin/vaadin-connect/issues/324
2. java file watcher instance remain running in this case, fixed in https://github.com/vaadin/vaadin-connect/pull/358
