### ISSUE TITLE
Missing output when Webpack build fails

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#82]
When the app is running (and webpack is watching file changes), if a change causes webpack to fail the console output is confusing:

```
🚀  Vaadin Connect Webpack has reloaded changes. 🚫 There are compilation errors in frontend code 🚫
```

#### Steps to reproduce:
 - start the starter with `npm start` (make sure it starts normally)
 - edit the index.js file so that it won't build (e.g. add a `import './non-existing.js';` line)
 - see that the console output is as above

#### Expected behavior:
When webpack build fails, then
 - the full error details are visible in the console
   ideally, there should be a full path to the file, a line number, and a position in the line pointing to the place that causes the issue
 - the message does not claim that the changes are reloaded: instead of _Vaadin Connect Webpack has reloaded changes_, it should be along the lines of _Vaadin Connect Webpack failed to build_ or similar.

**Comment by SomeoneToIgnore** [comment]
Verified that errors are displayed after https://github.com/vaadin/vaadin-connect/issues/324 is implemented and merged.
