### ISSUE TITLE
enable live reload for backend code / resources

### ISSUE THREAD

**Issue by vlukashov** [vaadin/base-starter-connect#9]
When changing a backend source file or a resource in the base starter project that is running locally in the dev mode, I want to see the changes applied in the browser in under 5 second after the changed source files are recompiled, so that I can have a quick feedback loop for my backend changes.

DoD:
 - no manual steps such as re-building the project or restarting the server are necessary
 - one manual page reload is acceptable
 - changed Java classes are hot swapped into the running app using Spring DevTools
 - changes in Java sources trigger regeneration of JS service wrappers
 - the README file is updated with the description of the live reload capabilities of the dev mode

**Comment by SomeoneToIgnore** [comment]
90% of the thing is done already, since we have a devtools dependency in the starter project – only two bullets need to be configured.

One thing worth investigating is the devtools – would be great to understand if they are configurable somehow.

**Comment by Legioth** [comment]
What do you want to configure?

**Comment by SomeoneToIgnore** [comment]
Do hotswap instead of restart whenever possible, perform additional tasks before or after the changes applied.

**Comment by Legioth** [comment]
Why?

**Comment by SomeoneToIgnore** [comment]
Former helps to speed up the redeploy, not really necessary, but nice to have.
Latter would be very helpful for us to hook up the regeneration trigger to.

**Comment by SomeoneToIgnore** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

See `DEVTOOLS PROPERTIES` for the configurable options.

**Comment by vlukashov** [comment]
works for me
